#!/bin/sh

if [ $1 = "launcher" ]; then
  dmenu_run -l 5 -p "$(date +'%d %a %H:%M')"
elif [ $1 = "terminal" ]; then
  x-terminal-emulator &
elif [ $1 = "volumeup" ]; then
  amixer set Master 3+
elif [ $1 = "volumedown" ]; then
  amixer set Master 3-
elif [ $1 = "printscreenarea" ]; then
  scrot -s
fi
